### ISSUE TITLE
Typescript compatibility issue?

### ISSUE THREAD

**Issue by taschmidt** [hbenl/vscode-mocha-test-adapter#101]
I added the following to my settings.json in vscode:

```
    "mochaExplorer.files": "src/**/*.test.ts",
    "mochaExplorer.require": [
        "ts-node/register/transpile-only"
    ]
```

This has always worked with other projects, but I've started using newer Typescript syntax, specifically optional chaining, i.e. `foo?.bar`. All other aspects of my project function as expected, both at runtime and when running mocha from the CLI. However, test explorer has started failing to load my unit tests. If I look at log window, it's giving me a `SyntaxError: Unexpected token '.'` on the optional chaining line.

Does anyone know a way around this?

**Comment by kingsimba** [comment]
I find testing TS files directly is very slow. When I click "run", it will cost 5 seconds to start on my AMD 1700X.
As comparison, when compiled into JS and run mocha on JS files, it start instantly.
See my sample project:  https://github.com/kingsimba/mocha-test-explorer-bug
Though I think there is a bug (#102) in this approach, but I've find a workaround.

**Comment by taschmidt** [comment]
Thanks but I would really rather not go that route since that really eliminates the convenience of having the plugin.

**Comment by hbenl** [comment]
This sounds like the optional chaining is not getting transpiled - have you set `"target": "ES2020"` in your `tsconfig.json`? If so, you need to ensure that the tests are run in a version of Node that supports optional chaining, try setting `mochaExplorer.nodePath` in your settings to point to such a version of Node.

**Comment by taschmidt** [comment]
Oh yeah, sorry, I got this resolved but forgot to come back and comment on it. A coworker had set it to "ESNext".
