### ISSUE TITLE
Can't show inline error message when compile TypeScript into JavaScript

### ISSUE THREAD

**Issue by kingsimba** [hbenl/vscode-mocha-test-adapter#102]
# Problem

After compiling from TypeScript compile to JavaScript, the test explorer cannot show the error message along side with the code.

# Reproduce Steps

1. Open this project with VSCode. https://github.com/kingsimba/mocha-test-explorer-bug
2. Ctrl + Shift + B, select 'tsc watch'.
   
   Source files in src/.ts will be compiled into test/.js along with the map file.

3. Open Test Explorer UI. Run all tests. There will be a failed test.
4. The test failed as expected. But these is NO error message along the code. See image below:

![image](https://user-images.githubusercontent.com/8407634/80448693-af054000-894f-11ea-82ac-8ea23e4d69b3.png)

# A workaround

1. Edit "tsconfig.json", remove "outDir". So JS files will be in the same folder as TS files.
2. Edit ".vscode/settings.json"::
   
      "mochaExplorer.files" : "src/**/*.spec.js"

The problem can be fixed. But it's messy to mix source files with build output files. Especially because they can't be ignored #103.

**Comment by hbenl** [comment]
Thanks for the sample project!
I fixed this in version 2.4.0.
