### ISSUE TITLE
unable find any suites when use delayed root suit

### ISSUE THREAD

**Issue by silenceu** [hbenl/vscode-mocha-test-adapter#110]
Hello, thank for your great extension!

I find this extension couldn't find test suits when use [delayed-root-suite](https://mochajs.org/#delayed-root-suite). Does this extension implement this function, or I my .mocharc.js file is wrong?

Here is my envirment:
- system: macOS 10.15.3
- vscode: 1.45.1
- Mocha Test Explorer: 2.4.0

.mocharc.js:
```js
module.exports = {
    delay: true,
    exit: true,
    file: ['server/app.js'],
    spec: [
        'test/top.test.js',
    ],
    timeout: 5000,
    env: {
        MOCHA_TEST: 'YES',
    }
}
```

test/top.test.js: 
```js
function importTest(name, path) {
    describe(name, () => {
        require(path);
    });
}

setTimeout(() => {
    describe('init', function () {
        before(function () {
           console.log('**************************************BEGIN**************************************');
        });
        importTest('account tests lodaing...', './account.test.js');
        after(function () {
            console.log('**************************************END**************************************');
        });
    });
    run();
}, 2000);
```

**Comment by hbenl** [comment]
Delayed root suites aren't supported yet, but I'll look into it.

**Comment by silenceu** [comment]
Ok, thank you for your contribution, I look forward to this feature! 🌷

**Comment by hbenl** [comment]
I have added `--delay` support to version 2.5.0. As usual, you can put it either in your Mocha configuration file or in your VS Code settings.
