### ISSUE TITLE
Tests runs unexpectedly if they share the same start words

### ISSUE THREAD

**Issue by kingsimba** [hbenl/vscode-mocha-test-adapter#117]
If I click RUN on "should work", "should work NOT" also runs.

https://github.com/kingsimba/mocha-test-explorer-bug/blob/d22c39097f57e69691e9ea195d79aaffd024c263/src/test.spec.ts#L6

**Comment by hbenl** [comment]
Fixed in version 2.6.2.
As always, thanks for the sample!
