### ISSUE TITLE
Not reporting errors for hooks

### ISSUE THREAD

**Issue by iangabrielsanchez** [hbenl/vscode-mocha-test-adapter#124]
Mocha Test Explorer doesn't report errors in before or beforeEach hooks, stuff like:
```
     TypeError: Cannot stub non-existent own property storeMessage
```
It just shows the stop icon and also doesn't show logs

**Comment by bellovic** [comment]
Same problem here. If hooks (for example `before()` fails it is shown only in `Mocha explorer log` and is not formatted or colored. I would expect error from hooks to be also shown in `Mocha Tests` tab formatted and colored. It also doesn't update UI with failed style.

**Comment by iangabrielsanchez** [comment]
https://github.com/hbenl/vscode-mocha-test-adapter/issues/71#issuecomment-568727230
>Yes, this is by design: the Test Explorer log is used to show the messages from a single test, but the messages from the before/after/setup/teardown steps can't be linked to any test, so they only show up in the "Mocha Tests" output channel (which I introduced specifically to make sure that there is a place where you can find all messages, including those that can't be linked to any test)
