### ISSUE TITLE
Cannot get opts parameter async-only to work with mocha test adapter

### ISSUE THREAD

**Issue by cmb0335** [hbenl/vscode-mocha-test-adapter#129]
I am setting "async-only" in the .mocharc.* config file, but the test adapter does not seem to use it.

I am converting a project where some of my test are not returning promises, but they are passing in the mocha test explorer.

If I just use the command line and pass --async-only, these tests will fail.

**Comment by hbenl** [comment]
That option currently isn't supported, I'll add it to the next release.

**Comment by cmb0335** [comment]
Thank you. Would it be worth adding the rest of the command line options also?

**Comment by hbenl** [comment]
I've added support for this flag in version 2.9.0

> Would it be worth adding the rest of the command line options also?

Not all options make sense for this extension, I've tried to add all that do.
