### ISSUE TITLE
Can multiple paths be provided for the "files" setting?

### ISSUE THREAD

**Issue by v-kydela** [hbenl/vscode-mocha-test-adapter#131]
I have a Node package with the following test script: `nyc mocha \"libraries/@(adaptive*|bot*)/tests/**/*.test.js\"`

I tried putting the line `"mochaExplorer.files": "libraries/@(adaptive*|bot*)/tests/**/*.test.js",` in my settings.json file in order to make Mocha Test Explorer run the same tests as my test script, but then it couldn't find any tests. It seems the `@(adaptive*|bot*)` syntax isn't supported. Is there any way to get that same effect, i.e. providing two different search patterns?

**Comment by hbenl** [comment]
Try setting `"mochaExplorer.files": ["libraries/adaptive*/tests/**/*.test.js", "libraries/bot*/tests/**/*.test.js"]` in your settings.
