### ISSUE TITLE
can't figure out how to ignore certain files

### ISSUE THREAD

**Issue by jmagaram** [hbenl/vscode-mocha-test-adapter#143]
I've got it all working. But if I edit and save the README.md file in the root of my project and press save, all the tests go "gray", meaning they are somehow out-of-date and need to be run again. I've tried adding "ignore" settings but it doesn't have any effect.

Here is my VS Code workspace settings. So it looks to me like the only tests that should be run or looked at are ones in the `firebase-tests` folder. So I don't understand why changing the README.md file at the root would affect anything.

    {
      "mochaExplorer.files": "firebase-tests/**/*.ts",
      "mochaExplorer.require": ["ts-node/register"],
      "mochaExplorer.env": {
        "TS_NODE_COMPILER_OPTIONS": "{\"module\":\"commonjs\"}"
      },
      "mochaExplorer.autoload": true
    }

I tried adding this `.mocharc.json` to the root folder but it has no effect.

    {
      "ignore": ["./README.md"]
    }

Actually, editing ANY file in my project, even a .scss file several folders down, causes the tests to become grayed out.

**Comment by hbenl** [comment]
Mocha Test Explorer doesn't know which files could influence your tests, so it assumes that all of them could.
