### ISSUE TITLE
global fixtures are not setup / teared down

### ISSUE THREAD

**Issue by avakhit** [hbenl/vscode-mocha-test-adapter#147]
I've implemented global fixture setup/teardown as suggested by mocha: https://mochajs.org/#global-setup-fixtures

I can start tests from command line ant it works as expected. If I start tests wia Mocha test explorer, setup/teardown is not called. Ist it a bug/desired behaviour or am I doing something wrong?

**Comment by hbenl** [comment]
Global fixtures are not supported yet, but I'll add support soon.

**Comment by hbenl** [comment]
I just published version 2.11.0 with support for global fixtures.
