### ISSUE TITLE
Doesn't follow import/require for test location

### ISSUE THREAD

**Issue by TheUnlocked** [hbenl/vscode-mocha-test-adapter#151]
Mocha doesn't allow for merging test suites with the same name (e.g. when split across multiple files), so as a workaround, I'm attempting to import/require tests like this:

```ts
// index.spec.ts
describe('parse', () => {
    require('./strings.spec');
    require('./numbers.spec');
});

// strings.spec.ts
describe('strings', () => {
    // ...
});

// numbers.spec.ts
describe('numbers', () => {
    // ...
});
```
Or alternatively:
```ts
// index.spec.ts
import stringsSpec from './strings.spec';
import numbersSpec from './numbers.spec';

describe('parse', () => {
    stringsSpec();
    numbersSpec();
});

// strings.spec.ts
export default () => describe('strings', () => {
    // ...
});

// numbers.spec.ts
export default () => describe('numbers', () => {
    // ...
});
```

In both cases, the test explorer successfully obtains all of the tests, but the source buttons only link back to `index.spec.ts` and the CodeLens only appears on the `require()`/`import xxx` lines to test the entire sub-suite, not on each individual test.

I'm using `"require": "ts-node/register"` in my mocharc rather than testing from compiled javascript with sourcemaps, and I have tried both with the monkey patch on and off to no avail.

**Comment by hbenl** [comment]
The problem is that the extension trusts Mocha to find the right file for a test, but in your setup Mocha thinks all tests are located in `index.spec.ts`. So I've added a new setting `mochaExplorer.multiFileSuites`: set it to `true` and the extension will ignore what file Mocha thinks a test is located in.
Please try it out and tell me if it works for you.

**Comment by TheUnlocked** [comment]
I now seem to be encountering #158 on Windows (will post more details there), but if I run vscode through wsl, this change works perfectly. Thank you!
