### ISSUE TITLE
TypeError: Cannot read property 'before' of undefined

### ISSUE THREAD

**Issue by williamlac** [hbenl/vscode-mocha-test-adapter#155]
Version 2.11.1 broke my Test Explorer.
It shows the error "TypeError: Cannot read property 'before' of undefined" and it points me to this line:
export default function processTests():void {
    describe('Process', () => {
        before(async () => { ...            <-------- This line.

My tests are exported as functions in different files, and I run them using this code:
import processTests from './process.spec';
describe('app', () => {
... befores and afters
    processTests();
    otherTests();
    otherTests();
    otherTests();
});

I downgraded to 2.11.0 and it's working as expected.

**Comment by hbenl** [comment]
I can't figure out how the changes in 2.11.1 can have that effect.
Could you create a sample repo that lets me reproduce the issue? Alternatively you could [enable logging](https://github.com/hbenl/vscode-mocha-test-adapter#troubleshooting) and attach the log file (but a sample repo would probably be much more useful).

**Comment by hbenl** [comment]
I think this is the same issue as #158. Could you verify this? Do you `require` or `import` the `describe` function in your test files? If so, remove that `require`/`import` (which is unnecessary and produces errors on Windows) and see if it fixes the problem.

**Comment by williamlac** [comment]
Sorry i took so long to respond!
That was the problem, VS Code automatically imported before from mocha in one of my files, and after the update that started showing the error.
Fixed!
