### ISSUE TITLE
No codelens or gutter state

### ISSUE THREAD

**Issue by jods4** [hbenl/vscode-mocha-test-adapter#16]
I am using Typescript tests, thanks to `--require ts-node/register`.

Works great, tests are found by the test explorer (after updating the glob `mochaExplorer.files` in workspace settings), run and are properly reported.

Except, I don't get the codelens decorators to run tests nor the test state in gutter. Looks like my `.spec.ts` file is not changed at all by this extension. `testExplorer.codeLens` and friends have their default value (true).

This is a bit strange because the extension is perfectly able to link the tests in explorer with their source line: clicking on the "goto source file" icon in Test Explorer works fine.

**Comment by jods4** [comment]
Yes I'm on Windows.
It's a pain but for x-plat one really needs to always normalize paths (e.g. make `\` -> `/`) before comparing 😞 

My setup is the most basic there is: just a calculator test, except it uses TS.

Here's my workspace config, there's no `mocha.opts`: 
```json
{
  "mochaExplorer.cwd": "packages/test-runner",
  "mochaExplorer.files": "packages/test-runner/test/**/*.spec.ts",
  "mochaExplorer.mochaPath": "packages/test-runner/node_modules/mocha",
  "mochaExplorer.require": "ts-node/register"
}
```
Test:
```ts
import { sum } from "../lib/calc";
import expect = require("expect");

describe("Calculator", () => {
  it("should sum properly", () => {
    expect(sum(3, 2)).toBe(5)
  })
})
```

**Comment by hbenl** [comment]
I leave the path handling to VS Code and that works, but I keep making mistakes in that area (like this time). I just released a fix.

**Comment by jods4** [comment]
It works!
Thanks, that was so quick. You're a boss. ❤️
