### ISSUE TITLE
Test adapter doesn't build typescript source code

### ISSUE THREAD

**Issue by rallets** [hbenl/vscode-mocha-test-adapter#161]
Hi, I'm using typescript and Mocha test adapter to run some unit tests in VS Code, it's a great tool!
Everything works fine but I need to transpile the typescript code manually (via `npx tsc`) every time I edit the code... that's 
 a bit annoying. If I don't do that, the test will run on the old transpilation.
There is a way to run something like `npx tsc` before a test run? or am I missing a configuration somewhere?
Thank you

**Comment by hbenl** [comment]
You should use a watcher, that will transpile each change as soon as you save it (and will be a lot faster than starting `tsc` and transpiling *all* sources every time). It's available by default as a task in VSCode: go to the Command palette and select "Tasks: Run Task" -> "typescript" -> "tsc: watch".

**Comment by rallets** [comment]
So there is no configuration (kind of trampoline) available in the adapter? is the watcher the only option? (so I can avoid that extra manual step)

**Comment by hbenl** [comment]
No, the adapter currently doesn't have such an option. If you want to avoid the extra manual step, you can configure the watcher to be run automatically (see [here](https://code.visualstudio.com/Docs/editor/tasks#_run-behavior), in fact I use such a [watcher task for this extension](https://github.com/hbenl/vscode-mocha-test-adapter/blob/65645f68a6678a288f0f7de782d71a56bc9edd76/.vscode/tasks.json#L5-L14)). Alternatively you can run your tests using `ts-node` (e.g. by adding `"require": "ts-node/register/transpile-only"` to `.mocharc.json`), then your sources will be compiled on-the-fly every time you run your tests (with the obvious performance hit).
