### ISSUE TITLE
Tests not re-run after saving changed test file

### ISSUE THREAD

**Issue by ralfhandl** [hbenl/vscode-mocha-test-adapter#162]
When changing a test file and saving it, the "Test Explorer: Reload tests" round arrow in the Test Explorer spins, but the tests are not rerun / the test results are not updated.

I`ve intentionally broken a test and saved it: arriw spins, but explorer bar still shows it green - Log is attached
[mocha-test-explorer.txt](https://github.com/hbenl/vscode-mocha-test-adapter/files/6634024/mocha-test-explorer.txt)

When pressing the "Run" code-lens or "Rerun all tests", the test shows red.

Auto-rerun works when changing and saving source files in `lib` folder.

**Comment by hbenl** [comment]
I just fixed this in version 2.12.1, thanks for the bug report.
