### ISSUE TITLE
"spec" configuration option not read?

### ISSUE THREAD

**Issue by atava** [hbenl/vscode-mocha-test-adapter#163]
The Test Explorer does not seem to be reading the "spec" configuration option, which is the one specifying which files are tests for Mocha.
This is the entry I have in the `.mocharc.json` file (any ".test." file in any subfolder except for node_modules):
```
{
  "spec": "!(node_modules)/**/*.test.{js,cjs,mjs}"
}
```

If I run Mocha through `npm run test` it works and the option is read, while the explorer is not showing the files.
The explorer runs fine if I add the glob pattern to its settings (`"mochaExplorer.files": "!(node_modules)/**/*.test.{js,cjs,mjs}"`), so I'm guessing it's just the configuration option not being taken into account for some reason.

**Comment by hbenl** [comment]
That's strange, this works for me. Please enable diagnostic logging as described in the [troubleshooting section](https://github.com/hbenl/vscode-mocha-test-adapter#troubleshooting) and attach the logs here.

**Comment by atava** [comment]
Browsing the options I think I've found the culprit here:
```
    "mochaExplorer.configFile": "",
```
I think I may have clicked on the _Edit on settings.json_ button for many options when I tried out the explorer first, and that option is set to a blank value by default and I must have left it that way.

I guess I may close this (the tests are read with the Mocha config file now). Thanks
