### ISSUE TITLE
Test Suite will not run if using string template as its title

### ISSUE THREAD

**Issue by ctataryn** [hbenl/vscode-mocha-test-adapter#173]
Given the following title for a test suite:

```javascript
const rnd = generateRandomCode();
describe(`Assignment percent and complete ${rnd}`, function () {
//...
}
```

Running the test via the Test Explorer causes the following to be dumped to the "Mocha Explorer Log":

```
[2021-07-08 19:33:15.336] [INFO] Worker: Loading files
[2021-07-08 19:33:15.336] [INFO] Worker: Running tests
[2021-07-08 19:33:16.415] [INFO] Received {"type":"finished"}
[2021-07-08 19:33:16.420] [INFO] Worker finished
```

But no actual tests are run.

If I remove the `${rnd}` from the title that is passed to `describe` then everything works.

**Comment by ctataryn** [comment]
Oddly enough, sometimes it'll work if there are dynamic parts of the title (granted in the following example it's the `it()` title not the `describe()` title).

For example, I have the following function that I invoke in several places within my tests:

```javascript
function pointCloseTo(points, idx, x, y, tolerance = 0.1) {
    it(`Should exist`, () => {
        expect(points).to.not.be.null;
        expect(points[idx]).to.not.be.null;
    });
}
```

This causes Mocha Test Explorer to render the following in its tree, and I cannot run those tests:

![image](https://user-images.githubusercontent.com/435719/125111148-2b92c300-e0ab-11eb-9042-a33188fab319.png)

However, if I add a counter, it works just fine:

```javascript
let ctr = 0;
function pointCloseTo(points, idx, x, y, tolerance = 0.1) {
  // added random number to get rid of "Duplicate ID" warning from Mocha Test Explorer
    it(`Should exist ${ctr++}`, () => {
        expect(points).to.not.be.null;
        expect(points[idx]).to.not.be.null;
    });
}
```

![image](https://user-images.githubusercontent.com/435719/125111305-5da42500-e0ab-11eb-8abc-e93c13c23d87.png)

But if I change that `ctr` to be a random number, I can't run the tests again:

```javascript
function pointCloseTo(points, idx, x, y, tolerance = 0.1) {
    it(`Should exist ${Math.random() * 100}`, () => {
        expect(points).to.not.be.null;
        expect(points[idx]).to.not.be.null;
    });
}
```
![image](https://user-images.githubusercontent.com/435719/125111479-947a3b00-e0ab-11eb-81a6-93f420426498.png)

If I look at the Mocha Test Explorer output log, the test that can't be run will issue the following output:

```
[2021-07-09 16:51:38.126] [INFO] Worker: Loading files
[2021-07-09 16:51:38.127] [INFO] Worker: Running tests
[2021-07-09 16:51:39.005] [INFO] Received {"type":"finished"}
[2021-07-09 16:51:39.009] [INFO] Worker finished
```

Is there a rule about what can be contained within these titles? I don't understand why the integer counter seems to work, but the random number doesn't.

**Comment by hbenl** [comment]
You can use string templates (and dynamically created titles in general) as long as they are deterministic: the titles are used to identify the tests and if you generate non-deterministic titles, this extension won't recognize the tests anymore because they have different titles when you try to run them than the titles they got when you loaded them. In other words: mocha is being run multiple times by this extension (once each time you load the tests and once each time you run some of the tests) and so the titles are generated multiple times.
