### ISSUE TITLE
mochaExplorer.env doesn't work in .mocharc.* files

### ISSUE THREAD

**Issue by clintonb** [hbenl/vscode-mocha-test-adapter#175]
My project uses `.mocharc.js` to configure Mocha. Adding `mochaExplorer` configuration does nothing. I am specifically trying to set environment variables. I was only able to set them by using `.vscode/settings.json`. Is this expected behavior? If so, please update the README to clarify usage of `.mocharc.*` files and how these settings should be configured.

Here is my `.mocharc.js` file:

```js
module.exports = {
  exit: true,
  recursive: true,
  reporter: 'mocha-multi-reporters',
  reporterOptions: {
    reporterEnabled: 'spec, mocha-junit-reporter',
  },
  // TODO Configure test output once issue resolved:
  //    https://github.com/stanleyhlng/mocha-multi-reporters/issues/60
  // mochaJunitReporterReporterOptions: {
  //   mochaFile: './test-reports/junit.xml'
  // },
  timeout: 5000,
  mochaExplorer: {
    env: {
      NODE_ENV: 'test',
    },
  },
};
```

**Comment by hbenl** [comment]
All the `mochaExplorer.*` settings need to go into your VSCode settings (`.vscode/settings.json`).

**Comment by clintonb** [comment]
@hbenl can you update the README to explicitly state this, please?

**Comment by hbenl** [comment]
@clintonb Yes, I'll do that. Sorry for the confusion.
