### ISSUE TITLE
Mocha Test Explorer restores deleted in git yaml spec files

### ISSUE THREAD

**Issue by ilog2000** [hbenl/vscode-mocha-test-adapter#176]
Mocha Test Explorer: v2.13.0
Visual Studio Code: 1.58.2
OS: Windows 10.0.19043

We keep some of test specs in yaml files. Recently discovered, that deleted (and committed) in git yaml files re-appear after loading the project in VSCode with Mocha Test Explorer addon. Disabling plugin stops restoring deleted files. Enabling recovers them again.

Unfortunately, I am not sure whether it happened prior to VSCode 1.58 release.

**Comment by hbenl** [comment]
This extension doesn't contain any code that writes files in your workspace (except if you use `mochaExplorer.logfile`), so the culprit must be somewhere else, sorry.

**Comment by ilog2000** [comment]
Does it use cache for test specs?

![Mocha Test Explorer](https://user-images.githubusercontent.com/4150856/126461764-2afa699e-9fbd-4e4d-8491-5167869a269a.gif)

**Comment by hbenl** [comment]
No, it doesn't.
But it does run all your test files as soon as it's enabled in order to "load" the tests (i.e. to get the tree of suites and tests that is shown in the Test Explorer). Perhaps one of your test files writes the yaml spec files?

**Comment by hbenl** [comment]
If you run `./node_modules/.bin/mocha --grep "$^"`, do you also see changes to your yaml spec files?

**Comment by ilog2000** [comment]
It's not even about running tests. Just enabling addon restores deleted files in a couple of seconds.

I see your point about writing any files in the extension. And of course, this addon is not a show stopper for me - mostly I run tests in the console. So, let's simply keep an eye on this weird behavior. I will try again after the next VSCode update and share my findings if any.

**Comment by hbenl** [comment]
> It's not even about running tests. Just enabling addon restores deleted files in a couple of seconds.

That's what I was trying to explain: when you enable the extension, it will immediately load (but not run) the tests and it does so by doing an empty test run. You can do an empty test run using `./node_modules/.bin/mocha --grep "$^"` (that will run all tests that match the regular expression `$^`, but that regular expression doesn't match anything). So if my theory is correct and one of your scripts writes those files, it should also happen when you run that command.

**Comment by ilog2000** [comment]
I tried your suggestion as `./node_modules/.bin/_mocha --recursive --require @babel/register --exit ./test/_init.js --grep "$^"` because it's more complex in my case (`_init.js` loads .env file with settings, nothing else).

I got `0 passing (2ms)` in response, and `git status` shows no restored yaml files. Is this what you meant, or I'm missing something?

**Comment by hbenl** [comment]
Yes, this is what I meant. If you post the relevant mocha configuration (in VSCode settings and/or mocha config files), I could check that it corresponds to the command line you have given.
