### ISSUE TITLE
where can I find the error log

### ISSUE THREAD

**Issue by jan4984** [hbenl/vscode-mocha-test-adapter#177]
![image](https://user-images.githubusercontent.com/3941368/127622479-acba20dc-fac4-43d8-920c-f5f8d2513dea.png)

**Comment by hbenl** [comment]
Well, you are seeing the regular error log ("The worker process finished with code 1 and signal null"). Usually it contains more useful information, but not in this case, so we need to dig deeper: you can [enable diagnostic logging](https://github.com/hbenl/vscode-mocha-test-adapter#troubleshooting), hopefully that will contain the info you need (if you use the `mochaExplorer.logpanel` setting, it will create an output panel called "Mocha Explorer Log").

**Comment by jan4984** [comment]
Thanks. In `describe`  function top-most scope, there's a exception, after fixing that, it's OK now. Is it a kind of bug, should the explorer just parse the test files?
