### ISSUE TITLE
Remove vscode-test-explorere dependency

### ISSUE THREAD

**Issue by rickstaa** [hbenl/vscode-mocha-test-adapter#184]
I think we should remove the dependency to the [vscode-test-explorer](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) since it will be deprecated now the vscode test API has been finalized (see [this announcement](https://github.com/hbenl/vscode-test-explorer#migrating-to-native-testing)). I quickly tried to remove this dependency myself in #33 but received the following errors when building:

```bash
src/core.ts:354:115 - error TS2571: Object is of type 'unknown'.

354       this.testsEmitter.fire(<TestLoadFinishedEvent>{ type: 'finished', errorMessage: `Couldn't establish IPC:\n${err.stack}` });
```

I don't think there are related to the code changes I made are related. I sadly don't have time to investigate this further due to some pressing deadlines.

**Comment by hbenl** [comment]
See https://github.com/hbenl/vscode-mocha-test-adapter/pull/183#issuecomment-974859253
