### ISSUE TITLE
Crash on basedir lookup: TypeError: Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by allanpaiste** [hbenl/vscode-mocha-test-adapter#186]
Caused by the following line:

https://github.com/hbenl/vscode-mocha-test-adapter/blob/80a8613a076d94cba3602d750317b8aac02d1b4a/src/worker/patchMocha.ts#L145

... that does not take into account the fact that stack file might not always be set.

In my case this happened when using Mocha extensions that enable test-cases where the violating frame was:

```javascript
 {
    fileName: null,
    lineNumber: null,
    functionName: 'Array.forEach',
    typeName: 'Array',
    methodName: 'forEach',
    columnNumber: null,
    native: false
  }
```

**Comment by hbenl** [comment]
Fixed in version 2.13.2. Thanks for the bugreport.
