### ISSUE TITLE
Issues when enabled option "Test Explorer: Use Native Testing"

### ISSUE THREAD

**Issue by jruales** [hbenl/vscode-mocha-test-adapter#196]
When enabling this option in the settings:
![image](https://user-images.githubusercontent.com/1588988/156456785-b8b631fc-e408-4b05-bb20-b2d3fd6c7c12.png)

Then there are some issues that happen.

The folders aren't listed anymore in multi-root workspaces. See:
https://github.com/microsoft/vscode-test-adapter-converter/issues/28

Furthermore, some inline UI elements are gone (run test, debug test, reveal in test explorer)

**Comment by hbenl** [comment]
- I have create microsoft/vscode-test-adapter-converter#29 for microsoft/vscode-test-adapter-converter#28.
- in the native testing UI running/debugging/revealing tests can be accessed through the gutter icon's context menu: 
![Screenshot_2022-03-05_13-56-18](https://user-images.githubusercontent.com/16060807/156884148-ed6025a9-1da6-4d28-b932-24e6cda03e4d.png)
