### ISSUE TITLE
Coloring of test result output isn't preserved

### ISSUE THREAD

**Issue by jruales** [hbenl/vscode-mocha-test-adapter#197]
When running tests in the terminal, the output has nice ANSI coloring with green and red to indicate changes:
![image](https://user-images.githubusercontent.com/1588988/158260179-972ebe21-32a0-4575-8c8d-b92b2deee9dc.png)

This coloring is completely removed in the UI when looking at a test output.

Could this ANSI coloring be preserved?

**Comment by hbenl** [comment]
Unfortunately no. The extension uses a VS Code output channel and that doesn't support coloring.
