### ISSUE TITLE
Add ability to set mocha options

### ISSUE THREAD

**Issue by sourcier** [hbenl/vscode-mocha-test-adapter#2]
As a user,
I would like to be able to pass run time options to mocha, a config node similar. to:

```
"mocha.options": {
   "compilers": "ts:ts-node/register"
},
```

Would be ideal.

**Comment by hbenl** [comment]
I already support _some_ mocha run time options (`ui`, `timeout`, `retries`, `require`, `exit`) and you could configure them like this:
```
"mochaExplorer": {
    "files": "test/**/*.js",
    "ui": "bdd",
    ...
}
```
Is this issue about adding more options or about the configuration layout?

**Comment by sourcier** [comment]
Adding more options, I would like to be able to pass the “compilers” option to mocha, I’m working on a typescript project.

**Comment by hbenl** [comment]
According to the Mocha documentation, `compilers` is deprecated and [should not be necessary](https://github.com/mochajs/mocha/wiki/compilers-deprecation):

> `--compilers` is redundant; we've yet to encounter a real-world situation in which the solution couldn't be expressed using `--require`.

Is there a reason why you can't switch to `require`?

**Comment by sourcier** [comment]
I was under the impression both settings were required, I'll use --require.
