### ISSUE TITLE
Running test suite from Test Explorer does not kill/stop the worker 

### ISSUE THREAD

**Issue by ivorynoise** [hbenl/vscode-mocha-test-adapter#207]
I'm not sure if this is a test explorer thing, or a mocha-test-adapter thing, so let me know if it should go in another place.

### Context:
The test explorer discovers and shows the tests properly:
<img src="https://user-images.githubusercontent.com/11216794/163728804-ccb4a42c-aad9-4d81-8a23-256e880382be.png" width="350" height="400">

When I run mocha manually via `npx mocha`, I don't get any `EADDRINUSE` leftover but I get it sometimes when I run via Test Explorer. 

The entire test suite can be found [here](https://github.com/makinhs/toptal-rest-series/blob/19594e3b65e2d8aa2abbc6e61fe05ad2ad866217/test/app.test.ts) & [here](https://github.com/makinhs/toptal-rest-series/blob/19594e3b65e2d8aa2abbc6e61fe05ad2ad866217/test/users/users.test.ts). 

The behavior is not consistent, in that it is stopped sometimes and not stopped sometimes. 

### A. The Mocha Explorer Log has the following:
```
.
.
.
1 [2022-04-17 18:46:32.688] [INFO] Received {"type":"suite","suite":"/Users/janedoe/Documents/devel/test/users/users.test.ts: users and auth endpoints with a valid access token","state":"completed","description":"37ms"}
2 [2022-04-17 18:46:32.691] [INFO] Received {"type":"suite","suite":"/Users/janedoe/Documents/devel/test/users/users.test.ts: users and auth endpoints","state":"completed","description":"150ms"}
3 2022-04-17 18:46:32.692] [INFO] Received {"type":"suite","suite":"undefined: ","state":"completed","description":"155ms"}
4 [2022-04-17 18:46:32.721] [INFO] Worker finished
5 [2022-04-17 18:47:08.896] [INFO] Worker finished with code null and signal SIGKILL
```

### B. Terminal output
```
1 $ lsof -i -P -n | grep 3000
2 node      99827 janedoe   24u  IPv6 0xe511641ecbf78ca3      0t0  TCP *:3000 (LISTEN)
3 $ kill -9 99827  
```

Line `A.5` is printed as a result of action `B.3`

### VS Code Config
```
    "testExplorer.useNativeTesting": false,
    "testExplorer.sort": "byLocation",
    "mochaExplorer.pruneFiles": true,
     // Issue with EADDRINUSE: https://github.com/hbenl/vscode-mocha-test-adapter/issues/28
    "testExplorer.showOnRun": true,
    "mochaExplorer.logfile": "/tmp/mocha-explorer.log",
```

### `.mocharc.jsonc`
```
// CLI: mocha -r ts-node/register 'test/**/*.test.ts' --unhandled-rejections=strict"
// https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.js
{
  "recursive": true,
  "require": "ts-node/register",
  "spec": ["test/**/*.ts"],
  "node-option": ["unhandled-rejections=strict"],
  "watch-files": ["test/**/*.ts"],
  "bail": true
}
```

**Comment by ivorynoise** [comment]
#28

**Comment by hbenl** [comment]
This is most probably an issue in your tests. You can force the extension to kill the worker using mocha's `--exit` option (or `mochaExplorer.exit` in your VS Code settings).

**Comment by ivorynoise** [comment]
Thanks. This worked.

**Comment by webdevfrancisco** [comment]
I'm having similar issues, any help would be appreciated. 
https://stackoverflow.com/questions/74644237/how-can-i-kill-server-automatically-using-mocha-test-explore
