### ISSUE TITLE
Debug has no "skipFiles" option?

### ISSUE THREAD

**Issue by simonsen78** [hbenl/vscode-mocha-test-adapter#21]
Hi

When running tests using the debug codelens, or the debug icon in the sidebar, it seems that there is no way to specify any skipfiles, is this correct?

**Comment by hbenl** [comment]
It wasn't possible, but now I have added the [`mochaExplorer.debuggerConfig` configuration option](https://github.com/hbenl/vscode-mocha-test-adapter#custom-debugger-configuration) that lets you specify your own debugging configuration.
