### ISSUE TITLE
native test explorer compatibility

### ISSUE THREAD

**Issue by ethanj-auditboard** [hbenl/vscode-mocha-test-adapter#214]
any chance this currently or perhaps soon will support the native test explorer added in vscode 1.59?
https://code.visualstudio.com/api/extension-guides/testing

or does anyone know of an extension that supplies the equivalent?

**Comment by hbenl** [comment]
You can use the native testing UI with this extension by setting `testExplorer.useNativeTesting` to `true` in your VS Code settings.

**Comment by ethanj-auditboard** [comment]
I already tried that, but it then wants me to install a test extension...

**Comment by hbenl** [comment]
Do you see any tests when you set `testExplorer.useNativeTesting` to `false`? I only see the prompt to install a test extension when I set `testExplorer.useNativeTesting` to `true` in a project where no tests are found by this (or any other testing) extension.

**Comment by ethanj-auditboard** [comment]
The test files are found correctly when I set `testExplorer.useNativeTesting` to `false`?
