### ISSUE TITLE
Group tests by outmost description

### ISSUE THREAD

**Issue by oguimbal** [hbenl/vscode-mocha-test-adapter#26]
Thanks for this great plugin.

My requtest is somehow related to #5
I have multiple files, describing the same outer feature.

```
// a1-spec.ts
describe('Feature A',()=>{
  describe('Sub feature A1', () => {
  });
});

// a2-spec.ts
describe('Feature A',()=>{
  describe('Sub feature A2', () => {
  });
});
```

Which are showing up in test explorer as:

- Feature A
-- Sub feature A1
- Feature A
-- Sub feature A2

Wouldnt it be expected to show up as below ?

- Feature A
-- Sub feature A1
-- Sub feature A2

(Test explorer is quite messy when you have hundreds of tests, being able to group them would be neat)

**Comment by ldorval480** [comment]
This would be super helpful.  The describes also don't seem to order themselves alphabetically or any way that I can discern so I cant group or order them that way.

**Comment by ljobse** [comment]
@oguimbal @hbenl 
I created a PR for this feature:
#58

**Comment by hbenl** [comment]
This is now available with the `testExplorer.mergeSuites` setting.
