### ISSUE TITLE
Customize CodeLense appearance

### ISSUE THREAD

**Issue by mikeerickson** [hbenl/vscode-mocha-test-adapter#31]
Is it possible to either hide or customize the style attributes for the CodeLenses?  They are quite obtrusive to me?

![image](https://user-images.githubusercontent.com/183153/51491078-181c0200-1d62-11e9-9883-4b53049b29e2.png)

**Comment by hbenl** [comment]
I can't influence the styling of the Code Lenses, but you can turn them off using
```
"testExplorer.codeLens": false
```
in your settings.

**Comment by mikeerickson** [comment]
Awesome, that will suffice (and I actually like this better)
