### ISSUE TITLE
Adapter doesn't reload the server after changes

### ISSUE THREAD

**Issue by prajjwaldimri** [hbenl/vscode-mocha-test-adapter#33]
For some reason, the plugin doesn't reload my server after making changes to the files. Id doesn't even stop after closing VS Code. I have to manually kill it after making any changes to the server. I enabled the exit flag option, prune option but nothing seem to work.

Any ideas what might be causing this?

Environment:
OS: Arch Linux
Node: 11.7.0

**Comment by hbenl** [comment]
What's the server you're talking about? What process are you killing manually?

**Comment by prajjwaldimri** [comment]
I start my graphql server using Apollo boost for testing the api. it doesn't get restarted when I change any files.

**Comment by hbenl** [comment]
How do you stop or restart the server when you use Mocha on the command line?

**Comment by prajjwaldimri** [comment]
I am using apollo-graphql-express in the server.js file after importing which I start the server. Then I use apollo-boost to mock client requests to the server.

Something like this

```
import app from "../server";
const { expect, assert } = require("chai");

app.listen(1337, "127.0.0.1");

const client = new ApolloBoost({
  uri: "http://localhost:1337/api"
});
```

**Comment by hbenl** [comment]
... but how is the server stopped after running the tests on the command line?

**Comment by prajjwaldimri** [comment]
I mean in case of when running mocha from command line it just exits and the server stops.

**Comment by hbenl** [comment]
I figured out what was happening: the server is also started when the tests are loaded (not run) and in that case, the exit option wasn't used. I have just published a fix that will kill the worker process (and hence the server) after loading the tests if the exit option is set.
Please test this and tell me if it works for you.

**Comment by prajjwaldimri** [comment]
Yup, it works now :) Thanks
