### ISSUE TITLE
Globbing support?

### ISSUE THREAD

**Issue by ManfredLange** [hbenl/vscode-mocha-test-adapter#34]
It appears as if there is no (sufficient) support for globbing.

This setting works:
```
"mochaExplorer.files": "src/**/*.micro.ts"
```

This setting doesn't:
```
"mochaExplorer.files": "src/**/*.+(micro|integration).ts"
```

See https://github.com/isaacs/node-glob#glob-primer for details about globbing.

I was wondering if this is a mistake on my end or whether it's unsupported by this extension.

Background: We have different types of tests that we distinguish using this naming convention.

**Comment by hbenl** [comment]
This surprised me as well. I'm using the `vscode.workspace.findFiles()` method and its documentation says that it uses glob patterns, but there seem to be many interpretations what a glob pattern actually is... 
On the page you linked to it says that the `+(a|b)` syntax is only available in "extglob" patterns. The [VS Code API docs](https://code.visualstudio.com/api/references/vscode-api#GlobPattern) don't mention this syntax, so I guess "extglob" is disabled.
But you can use `"src/**/*.{micro,integration}.ts"` (no idea where *that* syntax comes from). If that doesn't work you could use 2 globs (`"src/**/*.micro.ts"' and '"src/**/*.integration.ts"`) in your `mocha.opts` file. In the next version of this adapter I will also support multiple globs in `mochaExplorer.files`.

**Comment by ManfredLange** [comment]
```
"mochaExplorer.files": "src/**/*.{test,micro,integration}.ts"
```
did the trick. Thank you, Holger!

Also, just thought I'd mention that the plug-in is also pretty fast for repos/projects with thousands of mocha tests. Good experience. Well done!
