### ISSUE TITLE
Need option to save test before running.

### ISSUE THREAD

**Issue by mwinters-stuff** [hbenl/vscode-mocha-test-adapter#36]
I have found, that with the VSCode auto-save option turned off, editing a test then clicking "run" in the editor, that the test will run from the saved version of the code and not what was just edited. I have to save the file before clicking run.

I have not tried with autosave on, as I dont usually use that.

**Comment by Moglum** [comment]
Yes, please. 
It would be awesome to have a config option to enable/disable _Auto-save test file_  when running any test or suite from that files using CodeLenses. I've just spent way more time than I'm willing to admit on trying to fix a test before realizing all I need to do is save the file.
