### ISSUE TITLE
Add support for the new mocha 6 configuration files

### ISSUE THREAD

**Issue by Szauka** [hbenl/vscode-mocha-test-adapter#37]
Mocha 6 has implemented suppoert for new configuration files, https://mochajs.org/#configuring-mocha-nodejs, are there any plans to support this config files on this extension?

**Comment by hbenl** [comment]
Yes, I definitely want to support this, it may take some time though.

**Comment by hbenl** [comment]
I've just published version 1.7.0 which supports the new configuration files.
