### ISSUE TITLE
Async tests doesn't seem to be working properly

### ISSUE THREAD

**Issue by danilocode** [hbenl/vscode-mocha-test-adapter#39]
async tests seem to be tagged as failed even though they are passed.
A typical async test would look like this:
```
async someAsyncFunction() {
    return 1;
}
it('should pass', async() => {
        const a = await someAsyncFunction();
       expect(a).to.equal(1)
});
```

The test generally passes but sidebar shows it was failed

**Comment by hbenl** [comment]
Could you please give an example of an async test that doesn't work.

**Comment by danilocode** [comment]
It seems to be working now, 
Before that typical test which I just wrote above (you just need to add `describe`) did not pass but now it is passing
