### ISSUE TITLE
[ERROR] No active debug session - aborting

### ISSUE THREAD

**Issue by tvedtorama** [hbenl/vscode-mocha-test-adapter#40]
Hi, 

after rebooting my machine the excellent debug-feature does not work anymore.

It seems VS Code is attaching to some process, but leaves immediately.

In the diagnostics I get this: `[ERROR] No active debug session - aborting`

Anyone seen this error? 

These are my settings:

```json
   "mochaExplorer.files": "tests/**/*[!.d].ts",
    "mochaExplorer.require": "ts-node/register",
    "mochaExplorer.debuggerConfig": "DebugTSNodeTest",
    "mochaExplorer.debuggerPort": 9230,
    "mochaExplorer.logpanel": true,
```

If I try to change the port option, in the launch options, VSCode just hangs - leading me to think that something is launched and then exits.

**Comment by hbenl** [comment]
This is due to Microsoft/vscode#70125.
I have added a workaround in version 1.6.2, so after updating Mocha adapter, debugging will work again.

**Comment by tvedtorama** [comment]
Excellent, it debugs perfectly now.  Thank you!
