### ISSUE TITLE
it statements in loop don't show as pass/failed in gutter

### ISSUE THREAD

**Issue by Maldaris** [hbenl/vscode-mocha-test-adapter#41]
If I have the following test:

```
describe('some repeated test case', () => {
  const someDataSet = ['a','b','c','d'];

  someDataSet.forEach((item) => {
    it(`should do some operation for ${item}`, () => {
      expect(someDataSet.indexOf(item) > -1).to.be.true;
    });
  });
});
```

That it statement will not have any indicator for pass/fail if the top describe statement is run via the inline link. (retains the black square icon for un-run tests).

Optimally, there should be some gutter indicator that displays the tests as a group, and has a color that indicates passed/failed (with specifics as a tooltip), and display the first failure inline in the code pane.

**Comment by hbenl** [comment]
> That it statement will not have any indicator for pass/fail if the top describe statement is run via the inline link. (retains the black square icon for un-run tests).

This works for me:
![Peek 2019-03-12 17-49](https://user-images.githubusercontent.com/16060807/54219186-4ced3f80-44ef-11e9-938c-965d9bdf1b93.gif)

> Optimally, there should be some gutter indicator that displays the tests as a group, and has a color that indicates passed/failed (with specifics as a tooltip), and display the first failure inline in the code pane.

Well, the gutter decoration (when it works) shows the same state that a test suite containing exactly these tests would show.
I like the idea of showing the specifics in a tooltip, this could be a list of all tests with their states. Not sure what you mean by "display the first failure inline in the code pane".

**Comment by Maldaris** [comment]
Okay this might actually be the caveat from my environment; we use Lodash `_.each` for our tests. I suspect there's a difference between that and the native `.forEach`

Inline failure in the code pane meaning, in your above example, line 42 would have red highlighting with the exact failure message at the end of line.

**Comment by hbenl** [comment]
What states do these tests show in the tree view? And do they appear in the "onScaleClick" suite?

Anyway it's strange that there are no decorations and code lenses for your call to `it()`. This means that the adapter can't figure out the location for these tests. The location detection is a bit tricky/hacky but usually worked reliably so far. You could enable the log panel and search the log for "findCallLocation" - you'll see a message `Looking for <filename> in <stacktrace>`, that message may help explain why this fails.

**Comment by Maldaris** [comment]
<img width="200" alt="Screen Shot 2019-03-12 at 1 25 47 PM" src="https://user-images.githubusercontent.com/1953773/54221718-721b8700-44ca-11e9-890a-34a8489e7c0f.png">
Note that no actual it statements show up below that tree dropdown, even though it's expanded.

I'll give the log panel a shot & see what I find.

**Comment by hbenl** [comment]
Aha, so the adapter doesn't understand that these tests are part of this suite - this explains why the decoration next to `describe()` doesn't change when the tests are run.

**Comment by Maldaris** [comment]
It's been a convention to use Lodash for consistency/readability with the rest of our codebase, but this adapter has kinda infected my team 💯  Is this something you expect to fix or should we adapt for this specific case?

**Comment by hbenl** [comment]
I'm not sure this is related to lodash - I just tried an example with `_.each()` and it works for me.
I noticed in your screenshot you reference a variable `scale` without setting it - shouldn't it read `_.each(scaleLevels, (scale) => ...)`?

**Comment by Maldaris** [comment]
I'm feeling kinda dumb right now. You're absolutely correct.

Oddly enough though in similar that did have this issue, the same behavior existed until I toggled on auto-run.

**Comment by hbenl** [comment]
So does it work after that change?

**Comment by Maldaris** [comment]
This problem might run deeper; invoking this test suite directly through the CLI to confirm base line, and I'm actually not seeing it show up in the reporter. 

I'm going to go ahead and say upon closer inspection this isn't a problem with the extension and is something deeper. Thanks for taking a look at this regardless 🌮
