### ISSUE TITLE
Doesn't work with mocha-prepare

### ISSUE THREAD

**Issue by iredjee** [hbenl/vscode-mocha-test-adapter#42]
Using [mocha-prepare](https://github.com/enobufs/mocha-prepare) to execute initial scripts before running all tests. In terminal mocha works just fine, however I have "Error while loading tests" error message with this extension. From the output I assume that callback I'm using for mocha-prepare just not executed. Maybe you know the issue and can help to solve this. Thank you.

**Comment by hbenl** [comment]
Sorry for the delay, the problem is probably that `mocha-prepare` patches the mocha module that is in your `node_modules`, but this adapter uses its own bundled (and unpatched) mocha module by default. Try adding
```
"mochaExplorer.mochaPath": "node_modules/mocha"
```
to your workspace settings.

**Comment by iredjee** [comment]
Thanks for the reply! I've already tried to add this option to `settings.json`. The same result (

**Comment by hbenl** [comment]
Do you have `mocha` and `mocha-prepare` installed locally (in your project) or globally (or both)?

**Comment by iredjee** [comment]
Both installed locally in a project

**Comment by hbenl** [comment]
Then I don't understand why this is happening :(
Could you create a little sample project with which I can reproduce this?

**Comment by iredjee** [comment]
I've created demo repo here https://github.com/iredjee/vscode-mocha-example. And it works fine with mocha-prepare. Interesting, it doesn't work for our corporate project while for teammates Webstorm Test Explorer shows proper tests structure. I need to check what's incompatible with VSCode then... Sorry for inconvenience, we can close this ticket.

I've found another issue with demo project. Running all tests, debugging with configuration in "launch.json" works totally fine, However running single test in debug mode gives me an error with mocha-prepare. You can try yourself as well. Not sure if it's related to your adapter or not.

Thanks for you support @hbenl !

**Comment by hbenl** [comment]
Thanks, I tried and it works fine for me - including debugging using the debug icon in Test Explorer. The only error I get when debugging is a timeout if I don't hit F5 fast enough (for continuing after hitting the breakpoint) - but that error is actually correct: the default mocha config says that a test should not take more than 2 seconds and if I hit a breakpoint and don't continue fast enough then the test *does* take more than 2 seconds.
I'd be interested to see the error that is shown in your corporate project if you click on the "Error while loading tests" message - perhaps that contains a hint why it's not working in your project.

**Comment by iredjee** [comment]
Indeed, there is a mocha-prepare error in output (afterAll done), but tests work fine.
Sorry, can't share corporate stuff. It's complex and difficult to understand where the root cause comes from, still couldn't figure out. Anyways, thanks a lot for you support! Let's close this issue. Hope one day I'll find a way to make it work :)

**Comment by iredjee** [comment]
Oh I have finally found the reason! @hbenl 

I've updated my repo. If you try to pull it and check Test Explorer you will see the error "Error while loading tests". I have TODO's there, if you follow them Test Explorer will start working properly.

So the problem is on phase when Test Explorer tries to get the list of test names from files. This happens before "running tests" phase.

Let's say I have some empty `shared` object, and I need to fulfill it with some properties and data before running my tests. And in my test files I assume that `shared` object is already fulfilled. So when we run tests, everything is OK.

There are 2 ways to use `shared` object in test files.
1. Inside some function like `shared.data.messages`, which is not called directly when you require this file.
2. At the beginning of file like `const { data: messages } = required('path/to/shared')`, which is called directly when you require this file.

And I think, pitfall comes out with case 1 when Test Explorer tries to get the list of test names. I suspect it attempts to require files, and of course on this phase there is no `prepare -> beforeAll` called as we don't run tests. It means `shared` object is no fulfilled at this moment, so Test Explorer fails to get the list of test names.

Hope I explained in clear way :)
@hbenl reopening this ticket, hope to get your feedback about this

**Comment by iredjee** [comment]
Technically, 

`mocha-compare` patches `Mocha.run` method with pre-run hook. And when we call `Mocha.run` it first executes pre-run hook, then call `Mocha.loadFiles` to load all test files and then run them.

When you try to load test files into Test Explorer window on this line https://github.com/hbenl/vscode-mocha-test-adapter/blob/master/src/worker/loadTests.ts#L55 you call `Mocha.loadFiles` and it will fails to load files which are dependent of pre-run hook (see case 2 in previous comment).

**Comment by hbenl** [comment]
Awesome! With your explanation it all became clear and it was actually easy to fix (I now load the tests by doing an empty test run instead of calling `Mocha#loadFiles()` directly).
Try with the latest version (1.8.1) and tell me if it works for you.

**Comment by iredjee** [comment]
Works like a charm, thank you for operative work @hbenl !
