### ISSUE TITLE
Support for dotenv files?

### ISSUE THREAD

**Issue by pdfowler** [hbenl/vscode-mocha-test-adapter#44]
In my standard test config, I have the following script in my `package.json`:

```
"test": "cross-env NODE_ENV=test env-path -p test/.env mocha \"test/api/**/*.!(e2e).test.js\" --recursive --exit --compilers js:@babel/register",
```

The key being the setting of the `NODE_ENV` to "test", and the dotenv config path being set to the `.env` file in the test directory.

For now, I've copy-pastad my full test `.env` file into the `mochaExplorer.env` in my vscode user settings, but I'd love to just say:

    mochaExplorer.envPath="./test/.env"

Thoughts or suggestions?

**Comment by hbenl** [comment]
Sounds reasonable, I'll add this feature to one of the next versions.

**Comment by hbenl** [comment]
I've added this to the latest version. Note that it doesn't expand the variables in the dotenv file (like `env-path` does through `dotenv-expand`), currently it only uses the `dotenv` package to parse the dotenv file.

**Comment by pdfowler** [comment]
Works great! Many thanks 👍
