### ISSUE TITLE
Request: option to use the Node/V8 flag support in Mocha executable from Mocha 6

### ISSUE THREAD

**Issue by David-Else** [hbenl/vscode-mocha-test-adapter#47]
In Mocha 6 with Node 12 you can use something like:
```
mocha --experimental-modules
```
and add `“type”: “module”` to the package.json for your project, and Node.js will treat all .js files in your project as ES modules. No need to use the `"mochaExplorer.require": ["esm"]` anymore (I hope)

I can't find an option to add node flags, especially `--experimental-modules`. Have I missed them, or maybe there is currently no way to add them? I see you can use an .opts file, but that is not ideal, much better to have an option like the `"mochaExplorer.require":`. Cheers.

**Comment by hbenl** [comment]
Currently there is no way to add node flags. Even if you put them into a config file (`mocha.opts` or the new `.mocharc.*`) they would still be ignored by this adapter. I will investigate this.

**Comment by David-Else** [comment]
@hbenl Thanks for the info, I was about to spend some time trying to make that work, so you just saved me!

Just making it work in the `.mocharc.*` would be fantastic, node flags are supported by default:

https://boneskull.com/mocha-v6/#introducing-mocharc-whatever

> When run via mocha, Node.js and V8 flags are also supported in configuration files and package.json (mocha.optsalready did this)

I hope you can make it work, Node 12 ESM looks great and they plan to remove the `--experimental-modules` flag as soon as it goes LTS. Cheers!

**Comment by oguimbal** [comment]
FYI My pull request #69  adds support for this as a side functionality

**Comment by David-Else** [comment]
I am sure it works with ESM now, so closing as feature not needed.
