### ISSUE TITLE
Adapter disabled for this folder, loading cancelled

### ISSUE THREAD

**Issue by vennekilde** [hbenl/vscode-mocha-test-adapter#48]
No tests show up in the test explore after the latest version (1.9.0). 
The Mocha Explorer Log shows the following message:
`Adapter disabled for this folder, loading cancelled`

I can track this error to a change from a week ago
https://github.com/hbenl/vscode-mocha-test-adapter/commit/330d99a02b86157705a74622eccfb25d4f6a9085

I have no idea what is meant by the change, so any assistance on what needs to be changed, in order for the plugin to start working again would be great.
Until then, if anyone else faces the same issue, you can downgrade to 1.8.1 to solve it for now

**Comment by hbenl** [comment]
You can (re-)enable it with the command "Mocha Test Explorer: Enable for a workspace folder" (`mocha-explorer.enable`).
The reason for the change was that some projects contain test files (`./test/*.js`) but those are not meant to be run with Mocha. In the past, the adapter would try to load them anyway, which would usually cause an error to be displayed in the Test Explorer. Now you can explicitly disable the adapter for such a project, and if the adapter sees a project with test files but no Mocha configuration and without `mocha` in the (dev-)dependencies, it will ask you if you want to enable or disable the adapter for that folder. The adapter should only be disabled automatically if your project contains no Mocha configuration, no `mocha` dependency and no test files.

**Comment by vennekilde** [comment]
Thanks that solved the issue

Not sure why it would disable it automatically, as i have mocha as a dependency, a mocha.opts file inside my tests folder and multiple mocha test files. The only thing i can think of, is that the nodejs project, is located in a subfolder of the workspace, so maybe it missed it? even though all the mocha related paths are set using the mochaExplorer workspace settings
