### ISSUE TITLE
all tests disapear if you create two outermost describe sections with same text in different files.

### ISSUE THREAD

**Issue by clementshimizu** [hbenl/vscode-mocha-test-adapter#5]
I was trying to create nesting of tests using describe blocks.  I ran into a bug where if i had each file had describe blocks that were unique the text explorer would work as expected.  However, if i made a describe block that shared the same outer most text it would hide all tests in the UI.
For example if i wanted to add 'client' as a description to group all of the client classes into one group it would screw up the UI and hide the test.

clientClassA.test.ts
describe('client',()=>{
describe('clientClassA.ts',()=>{
it('test1',()=>{expect(true).to.be.true;}
})
})

clientClassB.test.ts
describe('client',()=>{
describe('clientClassB.ts',()=>{
it('test1',()=>{expect(true).to.be.true;}
})
})

**Comment by hbenl** [comment]
Thanks for the detailed description. I have just published version 1.0.2, which should fix this (as long as the describe blocks are in different files, they still have to have unique names within one file).
