### ISSUE TITLE
Support or workaround for TypeScript tests

### ISSUE THREAD

**Issue by dylanrenwick** [hbenl/vscode-mocha-test-adapter#50]
I write all my mocha tests in typescript, and run them with `mocha --recursive --extension ts -r ts-node/register test/`

Is there any way to reproduce this behaviour with the test adapter?
I've tried setting `mochaExplorer.files` to `test/**/*.ts`, but of course that just errors as it's trying to run them as js files.

**Comment by hbenl** [comment]
You'll also need to add `"mochaExplorer.require": "ts-node/register"` to your settings (this corresponds to `-r ts-node/register` in your command line).

**Comment by dylanrenwick** [comment]
Yup! That solved it!

Thanks for the timely response (and for the extension :) )
