### ISSUE TITLE
Performance issues when using this extension

### ISSUE THREAD

**Issue by oliversalzburg** [hbenl/vscode-mocha-test-adapter#56]
When I have this extension enabled, it causes VS Code to spawn several very resource expensive `rg` processes, looking for `test/**/*.js`. I reported this behavior at https://github.com/microsoft/vscode/issues/75314

It appeared as if setting `"mochaExplorer.files": "./test/**/*.js",` explicitly in my workspace settings might be a valid approach to work around this issue, but the same `rg` processes are still spawned.

I'm not sure if I'm missing something here.

**Comment by hbenl** [comment]
You mentioned in your vscode issue that the performance issue seems to be triggered by `rg` going through your `node_modules` folder, but it shouldn't even be looking in that folder when searching for `test/**/*.js`.

> It appeared as if setting "mochaExplorer.files": "./test/**/*.js", explicitly in my workspace settings might be a valid approach to work around this issue, but the same rg processes are still spawned.

I'm not surprised that `rg` is still called, after all this extension still needs to find your test files. Are you sure that `rg` is called with the exact same arguments in that case? Are they taking as long as without the `mochaExplorer.files` setting?

**Comment by oliversalzburg** [comment]
It doesn't really make a difference.

![image](https://user-images.githubusercontent.com/1658949/59629237-abefcf80-9142-11e9-8600-05fa021c1fbf.png)

The first peak is with `"mochaExplorer.files": "./test/**/*.js"` in my workspace settings. The second peak is with that setting removed.

The generated command lines are functionally identical:

With explicit `files`: `"c:\...\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g /./test/**/*.js -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !/.nyc_output -g !/mochawesome-report --no-ignore --follow --no-config --no-ignore-global`

Without explicit `files`: `"c:\...\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g /test/**/*.js -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !/.nyc_output -g !/mochawesome-report --no-ignore --follow --no-config --no-ignore-global`

The only difference is that I prefixed `./` in my pattern.

Why it would even traverse down into `node_modules`, I have no idea. Maybe that isn't even the case and their is a completely different issue at play here. But once I add `node_modules` to `files.exclude`, the issue is completely gone.

**Comment by hbenl** [comment]
Well, it seems that `rg` isn't nearly as clever as we all expected it to be...
I just released an update that always explicitly excludes `node_modules` from test file searches. Tell me if this fixes it for you.

**Comment by oliversalzburg** [comment]
It's like night and day. I can't even catch the `rg.exe` processes in my task manager any more and everything seems to work perfectly otherwise. Awesome!
