### ISSUE TITLE
"Root"/"Mocha" at top level

### ISSUE THREAD

**Issue by maziac** [hbenl/vscode-mocha-test-adapter#59]
I'm not sure if this is a misconfiguration/error in my test suite or something with the mocha test explorer.

I just started to use the test explorer on my test suite and its working.
However at top level there is an empty "Root" test suite.
![pic](https://user-images.githubusercontent.com/3081973/60755651-d078f200-9ff2-11e9-8925-c858af973373.jpg)

But in my test suite there is no such "suite" statement.

Furthermore there is "Mocha" at root level and all tests are collected  under this.
But I haven't configured any suite with this name.

I'm using mocha with "tdd" if that is of importance.

**Comment by hbenl** [comment]
I'm guessing that you have another Test Adapter installed (perhaps your own) and that adapter sends an empty root suite (with the label 'Root') when it doesn't find any tests. It should send no root suite instead (i.e. the `TestLoadFinishedEvent` should just be `{ type: 'finished' }`).
When the Test Explorer receives suites from multiple adapters, it will show the root suite of each adapter, the mocha adapter creates a root suite with the label 'Mocha'.

**Comment by hbenl** [comment]
By the way, I just added some documentation to [the API repo](https://github.com/hbenl/vscode-test-adapter-api) that also explains this (among other things).

**Comment by maziac** [comment]
Good hint. Now it's working. It was in fact my own test explorer adapter :-)
Thanks.
