### ISSUE TITLE
TypeScript: "Show source" navigates to js-file

### ISSUE THREAD

**Issue by maziac** [hbenl/vscode-mocha-test-adapter#60]
In TypeScript project.
Pressing on the "Show source" button navigates to the *.js file instead of the *.ts file.

See animated gif:
![mt](https://user-images.githubusercontent.com/3081973/60758119-c5828980-a013-11e9-98ae-0baad7574e15.gif)

Maybe that's important. Here are my settings:
    "mochaExplorer.ui": "tdd",
    "mochaExplorer.files": "out/tests/**/*.js",
    "mochaExplorer.require": "source-map-support/register",
    "mochaExplorer.logpanel": true,
    "mochaExplorer.monkeyPatch": false

**Comment by hbenl** [comment]
Try with `"mochaExplorer.monkeyPatch": true`: without the monkey-patch, `"mochaExplorer.require": "source-map-support/register"` won't work.

**Comment by hbenl** [comment]
(alternatively, you could try with `"mochaExplorer.require": "ts-node/register"`, obviously in that case you'd have to change `"mochaExplorer.files"` to point to the typescript files)

**Comment by maziac** [comment]
"mochaExplorer.monkeyPatch": true
does the job, thanks.

**Comment by nguerrera** [comment]
@hbenl I'm seeing the same symptom with monkeyPatch = true. It was working at one point and stopped working at some other point. I'm unsure if it was a change to our code or an extension update that changed things. Is there anything else I should try when this happens?
