### ISSUE TITLE
Feature Request: mochapack support

### ISSUE THREAD

**Issue by tyler36** [hbenl/vscode-mocha-test-adapter#62]
My build process uses webpack to compile my files so the standard mocha doesn't work for me.
Instead, I use mochapack (https://github.com/sysgears/mochapack) for testing.

I'd like to be able to use this extension, which would help me keep my phpunit & mocha(pack) tests in the same extension but I don't think it is currently supported.

I know it's probably a bit of a reach, but any chance of getting an update for support?

**Comment by hbenl** [comment]
I just looked at the mochapack source and I don't think this is feasible: this extension uses some internal mocha APIs and these don't seem to be accessible with mochapack :(

**Comment by tyler36** [comment]
Thank you for taking the time to look at it. I appreciate the effort.
