### ISSUE TITLE
sass transpiler support

### ISSUE THREAD

**Issue by MichaelSL** [hbenl/vscode-mocha-test-adapter#63]
Hi!

I'm setting up a test adapter for a project that uses `js` and `sass`.

I have added `"mochaExplorer.require": ["@babel/register", "node-sass"],` to config. It helped with JavaScript but not with styles.

Error:

```
components\Header\_styles.scss:1
(function (exports, require, module, __filename, __dirname) { $header-height: 60px;
                                                                            ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Module._extensions..js (module.js:654:10)
```

`webpack` config for sass:

```
test: /\.[s]css$/,
                loader: "style-loader!css-loader!sass-loader?modules&localIdentName=[name]---[local]---[hash:base64:5]"
```

Which module should I reference to work with sass?

**Comment by hbenl** [comment]
Are you able to run your tests on the command line? 
I can help translating Mocha command line arguments to a configuration for this adapter, but I'm not enough of a Mocha expert to help figuring out how to setup your Mocha tests. What strikes me as odd, though, is that you want to run a webpack bundle that includes CSS (so apparently it is intended for the browser) in Node.js (this adapter can only run tests in Node.js).

**Comment by MichaelSL** [comment]
Thank you for help!

Here is the npm script which runs tests
```
mocha --require @babel/register css-null-compiler.js ./tests/setup.js ./tests/ --recursive
```

I've added requires to the settings file:
```
"mochaExplorer.require": ["@babel/register", "css-null-compiler.js", "webpack-bundle-analyzer", "./tests/setup.js" ]
```

now it can't find `_mocha.describe`:
```
TypeError: (0 , _mocha.describe) is not a function
```

**Comment by MichaelSL** [comment]
Resolved removing excessive `describe` imports: mocha emits the definition into global namespace, so no need to import it int the test itself.
