### ISSUE TITLE
Single out current test when using a custom debugger config?

### ISSUE THREAD

**Issue by papandreou** [hbenl/vscode-mocha-test-adapter#64]
Hi! I have a custom debugger config that I use for launching the test suite in my app, and I just discovered this extension, which makes the whole experience much more user friendly! :tada:

The only thing that I cannot figure out is how to single out the current test when using the custom debugger config.

My current config looks something like the following. Most of the complexity comes from using `nvm` to pick the correct node version to use.

```js
    {
      "protocol": "inspector",
      "type": "node",
      "request": "launch",
      "name": "Mocha Tests",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
        "--timeout", "999999",
        "--colors",
        "-r", "patches.js",
        "tests/test-setup.js",
        "tests/**/*.js"
      ],
      "internalConsoleOptions": "openOnSessionStart",
      "runtimeExecutable": "${env:NVM_DIR}/nvm-exec",
      "runtimeArgs": [
        "node"
      ]
    }
```

... But that has all the test files hardcoded, so it runs every test. If I replace `"tests/**/*.js"` with `"${file}"` and set a breakpoint, it kinda works, but it still runs all the other tests in the given file.

My feeling is that for this to work, we'll have to pass `-g <regexp>` on the command like, analogous to https://github.com/hbenl/vscode-mocha-test-adapter/blob/e2a6a463249868555bb9dc7c3e6829ad9d525bf5/src/worker/main.ts#L113-L114 -- but it doesn't look like that's supported?

Maybe I'm misunderstanding how the custom debugger configs are supposed to be laid out. Is the worker also supposed to be involved somehow?

**Comment by hbenl** [comment]
When you debug your tests with this extension, it starts the worker script in a child process with the `--inspect-brk=...` argument and then tells VS Code to attach the debugger to that process. That means your custom debugger config can't influence how the worker script (and hence mocha) is launched.
If you want to launch it with a different version of node, you'll have to use the `mochaExplorer.nodePath` configuration property, but that will not allow you to figure out dynamically (with nvm) which node path to use.
Perhaps you could let `mochaExplorer.nodePath` point to a script that acts like node by launching node through nvm... I've heard of people doing this kind of stuff successfully with this extension, but I don't really know how that works.

**Comment by papandreou** [comment]
@hbenl, thanks for the explanation, that makes sense! :hugs:

I have it working now without `nvm` and the other cli options I needed in `mocha.opts`. Might try to get the `nvm` thing working at a later point, but I think I'll just live without it for now.
