### ISSUE TITLE
Support for vue cli projects

### ISSUE THREAD

**Issue by mika76** [hbenl/vscode-mocha-test-adapter#67]
Currently when I try it there are no tests found and I don't see any way to use it together...

**Comment by mika76** [comment]
Initially there were no test because of the extension being disabled, but once enabling it still didn't find any tests.

I have the default test in a basic newly created vue cli app in the tests/unit/example.spec.js

It seems that it's looking only in test/**/*.js (not plural tests) but I see no place in the config to change this? When I renamed the folder it then found the test but failed running it because it did not like the import statement...

**Comment by hbenl** [comment]
Are you using `vue-cli-service test` to run your tests?

**Comment by mika76** [comment]
Yeah currently `npm run test:unit` which runs `vue-cli-service`, but would love it integrated into vscode

**Comment by hbenl** [comment]
In that case it won't work with this adapter, sorry. The adapter needs to run `mocha` directly. Maybe it's possible to write a [worker script](https://github.com/hbenl/vscode-mocha-test-adapter/blob/master/src/worker/main.ts) and use it with `mochaExplorer.launcherScript`, but that would be a lot of work...
