### ISSUE TITLE
adapter should default to workspace's mocha, not bundled

### ISSUE THREAD

**Issue by cspotcode** [hbenl/vscode-mocha-test-adapter#74]
After experiencing #11 and reading about #53, I think the test adapter should use the workspace's `node` and `mocha` by default.

For any node project, I install mocha as a devDependency, so it lives in \<workspace root\>/node_modules/mocha.  When I run tests, I want it to read my workspace's config file according to the version of mocha I have installed.  It's inconvenient and error-prone to separately configure a VSCode flag to make this work.

It seems straightforward for the test adapter to use my workspace's copy of mocha.  You can use node's require APIs to locate it.  If it can't be found, fallback to the bundled copy.  You can also check version ranges, so for example incompatible versions of mocha are flagged, a warning is shown, the bundled version is used, etc.

**Comment by hbenl** [comment]
Yeah, my initial assumption that using a bundled version was the safest way to go turned out to be wrong. Version 2.2.0 will use `node_modules/mocha` if it exists (and the bundled mocha package otherwise).
