### ISSUE TITLE
Possible issue with foreach

### ISSUE THREAD

**Issue by kakins** [hbenl/vscode-mocha-test-adapter#77]
Not sure if I'm seeing the same thing as described here: https://github.com/hbenl/vscode-mocha-test-adapter/issues/41

I have tests run based on some data in a .json file, we'll call it `myItems` below.  I iterate over those items and run tests based on the result.  The operations are async because API calls are made.

Running any of the tests (either individually or in a group) do not seem to indicate a result in the explorer window.  It displays a blue in-progress indicator then returns to the grey stopped indicator.

```javascript
_.forEach(myItems, async function dyn(data) {

  describe(`My tests`, () => {
    // some setup

    before(async () => {
      should();
      // some more setup
    });

    it('should work', async () => {
      // do some test
    });
});
```

Initially I was suspect of the `forEach`, but I wonder if async has something to do with it?

**Comment by kakins** [comment]
Nevermind, seemed to be an issue with the mocha timeout setting.  My API calls were taking longer than the timeout period.

**Comment by kakins** [comment]
...Actually sorry.  The timeout issue mentioned above solved a different problem for me.  I'm still experiencing the original issue with the foreach.

**Comment by hbenl** [comment]
The issue is that there are multiple tests with the same name and the name is used to identify the tests. So when Mocha tells Test Explorer that the test called "should work" has passed / failed, Test Explorer doesn't know which test Mocha is talking about.
Test Explorer should show a warning message when you click on a test that doesn't have a unique name, but that message is never shown due to a bug in Test Explorer, which I will fix soon.
If you make your test names unique (e.g. by writing `it('should work for ' + data.id, ...)` (assuming that your `data` contains a property called `id`) then it should work.

**Comment by kakins** [comment]
I do have multiple tests, each with a unique name.  The name of the test is actually data-driven based on a configuration file. So my tests are actually like the following:

```
_.forEach(myItems, async function dyn(data) {

  const {data} = dataFromConfig;

  describe(`My tests: {data.title}`, () => {
    // some setup

    before(async () => {
      should();
      // some more setup
    });

    it('should work for {data.title}', async () => {
      // do some test
    });
});
```
Debugging hits the breakpoint inside the `describe()` block but not the `it()` block.  

However, running the tests from the mocha command line does execute this particular series of tests correctly.

**Comment by kakins** [comment]
Nevermind!  Interestingly it was a bug on my end, of course :)

An API call was failing in the `before()` method but failing silently.  Could that be something where the test runner could help by failing on uncaught exceptions?

**Comment by hbenl** [comment]
I don't want to modify Mocha's behavior any more than absolutely necessary (because any difference in behavior will confuse some users). So since Mocha doesn't fail I'm not going to change that.
