### ISSUE TITLE
BUG: Running an empty Describe runs all other tests in the suite.

### ISSUE THREAD

**Issue by meelash** [hbenl/vscode-mocha-test-adapter#79]
I have multiple files of tests already built. I create a new file and put this in it:

```
describe('some functionality', ()=> {
  
})
```
When I hit run on this single describe function, the test runner starts running the entire suite, as if I had pushed the run-all button.

If I put any pending test inside of the describe that it doesn't happen:
```
describe('some functionality', ()=> {
  it('should blah');
})
```

**Comment by hbenl** [comment]
Fixed in version 2.2.1.
