### ISSUE TITLE
Cannot be used to debug VSCode extensions

### ISSUE THREAD

**Issue by Zingam** [hbenl/vscode-mocha-test-adapter#87]
I tried very hard to use the extension for debugging the tests in https://github.com/microsoft/vscode-cmake-tools
It will either not find the tests or the modules of the extension.
The instructions are sketchy and unclear how to proceed.

**Comment by hbenl** [comment]
How do you run the tests without this extension? Here's what I tried:
```
./node_modules/.bin/mocha
-> No test files found
./node_modules/.bin/mocha out/test/**/*.js
-> Error: Cannot find module 'vscode' [...]
```

**Comment by Zingam** [comment]
Without the Mocha extension I can select in the Debug pane: Run and Debug: Launch Extension Tests to execute the unit tests in the vscode-cmake-tools directory.

**Comment by hbenl** [comment]
These tests use VS Code's test runner. Even though the test runner does use mocha itself, this extension only supports tests that are run by calling mocha *directly*.
There are some backend tests that can be run using this extension with the following settings:
```
    "mochaExplorer.ui": "tdd",
    "mochaExplorer.timeout": 999999,
    "mochaExplorer.require": "ts-node/register",
    "mochaExplorer.files": "test/backend-unit-tests/**/*.test.ts"
```
However, these are apparently not the tests that you're interested in.

**Comment by Zingam** [comment]
So the extension wouldn't support VSCode extension development?

**Comment by Zingam** [comment]
> These tests use VS Code's test runner. Even though the test runner does use mocha itself, this extension only supports tests that are run by calling mocha _directly_.

Could you, please, make this more explicit in the documentation.

**Comment by hbenl** [comment]
It's now possible to run `vscode-test` tests with this extension! There's some documentation [here](https://github.com/hbenl/vscode-mocha-test-adapter#running-vs-code-extension-tests-using-vscode-test) and a sample [here](https://github.com/hbenl/vscode-extension-samples/tree/test-explorer-integration/helloworld-test-sample).
