### ISSUE TITLE
Cannot click on stacktraces in log, cannot set --full-trace

### ISSUE THREAD

**Issue by alexkli** [hbenl/vscode-mocha-test-adapter#93]
When a test log shows a stacktrace in the "output" window, the filenames are not clickable:

```
AssertionError [ERR_ASSERTION]: property 'package' does not match
    at assertObjectMatches (test/mylibrary.test.js:57:20)
    at Function.<anonymous> (test/mylibrary.test.js:526:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This is due to mocha printing relative paths by default, but VS Code wants absolute paths: https://github.com/mochajs/mocha/issues/3383

One solution is to use `--full-trace` (see link), but while I can make it work for an `npm test` run in the terminal, I can't get it to work within the test explorer. I tried:

- putting in `test/mocha.opts` file
- put in `npm test` script which calls `mocha --full-trace ...`
- could not find an option of the extension

I think it would be nice to default test explorer's mocha run to set `--full-trace` so that it traces are clickable in VS code out of the box.

Versions:
- Mocha Test Explorer 2.2.2
- VS Code 1.43.0
- OSX 10.15.3

**Comment by hbenl** [comment]
I have added `--full-trace` support to version 2.5.0. As usual, you can put it either in your Mocha configuration file or in your VS Code settings.
I have not made it the default because I want the defaults to be as close to Mocha's default behavior as possible.

**Comment by alexkli** [comment]
> because I want the defaults to be as close to Mocha's default behavior as possible

In the context of VS code, which needs absolute paths, it would be the sensible default, no?

**Comment by hbenl** [comment]
> In the context of VS code, which needs absolute paths, it would be the sensible default, no?

Well, `--full-trace` does more than just show absolute paths, it also shows stack frames that are usually filtered out. I actually prefer the shorter, less noisy stack traces (although I do see the appeal of clickable stack traces - so I may still change my mind on this).
If you want `--full-trace` to be your default, you can add `mochaExplorer.fullTrace` to your user settings.

**Comment by alexkli** [comment]
Fair enough. Didn’t know it does more than absolute paths.
